AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "**/**/*_spec.rb"

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/LineLength:
  Exclude:
    - "**/**/*_spec.rb"

Metrics/ParameterLists:
  Max: 5

Layout/IndentationWidth:
  Width: 4

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

Layout/IndentHash:
  EnforcedStyle: consistent

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/FrozenStringLiteralComment:
  Exclude:
    - "**/**/*_spec.rb"

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

# This cop seems to flag ASCII-8BIT codings (which are needed)
Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true
